#!/bin/bash

VENV_DIR="$(dirname -- "${BASH_SOURCE[0]}")/.CAN-venv"

if ! command -v python3 &> /dev/null; then
    echo "Error: python3 is not installed or not in the PATH."
    return 1
fi

if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment in $VENV_DIR..."
    python3 -m venv "$VENV_DIR"

    if [ $? -ne 0 ]; then
        echo "Error: Failed to create the virtual environment."
        return 1
    fi
fi

source "$VENV_DIR/bin/activate"

echo "Installing dependencies..."
pip install --upgrade pip
pip install \
    numpy \
    pandas \
    scikit-learn \
    bayesian-optimization \
    hdbscan \
    tqdm \
    python-can \
    cantools \
    pandas

echo "Virtual environment setup complete. Run 'source $VENV_DIR/bin/activate' to use it."
